version: '2'
services:
  mongo:
    restart: always
    image: mongo
    container_name: mongo
    volumes:
      - ./data/db:/data/db
      - ./backups:/backups
    ports:
     - 27017:27017
    networks:
      - RocketChat

  # mongo-init-replica:
  #   image: mongo
  #   command: 'mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
  #   links:
  #     - mongo:mongo

  RocketChat:
    restart: always #unless-stopped
    image: rocketchat/rocket.chat
    container_name: RocketChat
    ports:
      - "127.0.0.1:3000:3000"  #[port number]:3000" # should be a free port above 1024
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/rocket
      - ROOT_URL=http://localhost:3000 #[domain name (including schema, e.g. http://)]
      - PORT=3000
        #- MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
        #- MAIL_URL="smtp://smtp.google.com"
      - ADMIN_USERNAME=amir
      - ADMIN_PASS=amir1234
      - ADMIN_EMAIL=amir.shamss20@gmail.com
    volumes:
      - ./uploads:/var/www/rocket.chat/uploads
    networks:
      - RocketChat

networks:
  RocketChat:
    external: false